# Generated by Django 4.0.4 on 2022-05-20 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generify', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playlist',
            name='song',
        ),
        migrations.AddField(
            model_name='playlist',
            name='song',
            field=models.ManyToManyField(to='generify.song'),
        ),
        migrations.RemoveField(
            model_name='user',
            name='playlist',
        ),
        migrations.AddField(
            model_name='user',
            name='playlist',
            field=models.ManyToManyField(to='generify.playlist'),
        ),
    ]
