# Generated by Django 4.0.4 on 2022-05-23 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generify', '0005_alter_playlist_cover'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='is_private',
            field=models.BooleanField(default=False),
        ),
    ]
