# Generated by Django 4.0.4 on 2022-05-30 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generify', '0006_playlist_is_private'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playlist',
            name='is_private',
        ),
        migrations.RemoveField(
            model_name='user',
            name='playlist',
        ),
        migrations.AddField(
            model_name='playlist',
            name='user_id',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
