# Generated by Django 4.0.4 on 2022-05-30 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generify', '0007_remove_playlist_is_private_remove_user_playlist_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='user_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
